# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelglm <- function(X, Ys, family, beta0, weights, offsets, tol, nthreads, it_max, trace, block_size) {
    .Call('_parglm_parallelglm', PACKAGE = 'parglm', X, Ys, family, beta0, weights, offsets, tol, nthreads, it_max, trace, block_size)
}

